[project]
name = "uber-rides-dashboard"
version = "0.1.0"
description = "A dashboard that help to find Uber Hot Zones for drivers"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pandas>=2.2.3",
    "plotly>=6.0.1",
    "scikit-learn>=1.6.1",
    "streamlit>=1.45.1",
]
